# @package _global_
defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
    direction: minimize
    n_trials: 20
    params:
      hyper_parameters.lr:
        type: float
        low: 0.0001
        high: 0.1
        log: true
      hyper_parameters.batch_size:
        type: categorical
        choices: [8, 16, 32, 64]
      hyper_parameters.epochs:
        type: int
        low: 5
        high: 50
