name: Code linting

on:
  pull_request:
    branches:
      - main

jobs:
  check-updated:
    uses: ./.github/workflows/check-branch-updated.yaml
    with:
      base: main

  format:
    name: Check code formatting
    needs: check-updated
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v7

      - name: Install dev dependencies
        run: uv sync --group dev

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files
